language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo fmt --all -- --write-mode=diff
    fi
  - cargo test --all

services:
  - redis-server
